import { Providers } from './providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { Box } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Real Estate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body>
        <Box maxWidth='1280px' m='auto'>
          <header>
            Navbar
          </header>
          <main>
            <Providers>{children}</Providers>
          </main>
          <footer>
            Footer
          </footer>
        </Box>
      </body>
    </html>
  )
}